<?php require_once __DIR__ . '/layout/header.phtml' ?>

<div>
    <form action="do_login" method="post">
        <label>Usuario</label>
        <input required name = "user" type="text">
        <label>Contraseña</label>
        <input required name = "password" type="password">
        <button type="submit">Iniciar Sesión</button>
    </form>
</div>

<?php require_once __DIR__ . '/layout/footer.phtml' ?>
