<?php require_once __DIR__ . '/layout/header.phtml' ?>

<div class="container text-center">
    <div class="row">
        <div>
            <?php $n=1;?>
                <p> 
                    <h3><?=$categoria->nombre?></h3>
                    <?=$categoria->descripcion?></br>
                </p>
        </div>
        <div>
            <table class="table">
                <thead class="thead-dark"> 
                <tr>
                    <td>NOMBRE</td>
                    <td>DESCRIPCION</td>
                    <td>STOCK</td>
                    <td>PRECIO</td>
                    <td></td>
                </tr>
                </thead>
                <?php foreach ($productos as $producto):?>
                    <tr>
                        <td><?=$producto->nombre?></td>
                        <td><?=$producto->descripcion?></td>
                        <td><?=$producto->stock?></td>
                        <td><?=$producto->precio?></td>
                        <td><a href='productos/<?=$producto->id_producto?>' class="link-detalle">Detalle/Descripción</a></td> 
                        <?php $n++;?>
                    </tr>
                <?php endforeach; ?>
            </table>
        </div>
    </div>
</div>

<a href="list_categorias">VOLVER</a>

<?php require_once __DIR__ . '/layout/footer.phtml' ?>
