<?php require_once __DIR__ . '/layout/header.phtml' ?>

<div class="container my-5">

    <section class="editOrDelete mb-5">
        <h3 class="fw-bold mb-4 text-center text-dark">Editar o Eliminar un producto</h3>

        <div class="table-responsive shadow-sm">
            <table class="table table-striped table-hover align-middle">
                <thead class="table-dark">
                    <tr>
                        <td>NOMBRE</td>
                        <td>DESCRIPCION</td>
                        <td>PRECIO</td>
                        <td>STOCK</td>
                        <td>FECHA</td>
                        <td>CATEGORIA</td>
                        <td></td>
                        <td></td>
                    </tr>
                </thead>
                <tbody>
                    <?php foreach ($productos as $producto): ?> 
                        <tr>
                            <td><?= htmlspecialchars($producto->nombre) ?></td>
                            <td><?= htmlspecialchars($producto->descripcion) ?></td>
                            <td><?= htmlspecialchars($producto->precio) ?></td>
                            <td><?= htmlspecialchars($producto->stock) ?></td>
                            <td><?= htmlspecialchars($producto->fecha_alta) ?></td>
                            <?php foreach ($categorias as $categoria): ?>
                                <?php if ($categoria->id_categoria === $producto->id_categoria): ?>
                                    <td><?= htmlspecialchars($categoria->nombre) ?></td>
                                <?php endif; ?>
                            <?php endforeach; ?>
                            <td class="text-center">
                                <a href="editProducto/<?= $producto->id_producto ?>" class="btn btn-warning btn-sm">Editar</a>
                            </td>
                            <td class="text-center">
                                <a href="deleteProducto/<?= $producto->id_producto ?>" class="btn btn-danger btn-sm">Eliminar</a>
                            </td>
                        </tr>
                    <?php endforeach; ?>
                </tbody>
            </table>
        </div>
    </section>

    <section class="add_producto">

        <form action="addProducto" method="post" class="card shadow-sm p-4 mx-auto" style="max-width: 600px;">
            
            <h3 class="fw-semibold mb-3 text-center">Añadir un nuevo producto:</h3>

            <div class="mb-3">
                <label>Nombre</label>
                <textarea name="nombre" class="form-control" rows="3"></textarea>
            </div>

            <div class="mb-3">
                <label>Descripcion</label>
                <textarea name="descripcion" class="form-control" rows="3"></textarea>
            </div>

            <div class="mb-3">
                <label>Precio</label>
                <input type="decimal" name="precio" class="form-control" required>
            </div>
            
            <div class="mb-3">
                <label>Stock</label>
                <input type="number" name="stock" class="form-control" required>
            </div>

            <div class="mb-3">
                <label>Fecha (xxxx-xx-xx)</label>
                <textarea type="date" name="fecha_alta" class="form-control" required></textarea>
            </div>

            <div class="mb-3">
                <label>Categoría:</label>
                <select name="idCategoria" class="form-select" required>
                    <?php foreach($categorias as $categoria): ?>
                        <option value="<?= htmlspecialchars($categoria->id_categoria) ?>"><?= htmlspecialchars($categoria->nombre) ?></option>
                    <?php endforeach; ?>
                </select>
            </div>

            <div class="text-center">
                <button type="submit" class="btn btn-success px-4">Agregar</button>
            </div>
        </form>
    </section>
</div>

<?php require_once __DIR__ . '/layout/footer.phtml' ?>