<?php require_once __DIR__ . '/layout/header.phtml' ?>

<div>
    <p>-Selecciona de este panel lo que desees administrar-</p>
    <div class="pie">
                <h2><a href="list_categorias">Categorias</a></h2>
                <img class="img-pie" src="images/RRSS.jpeg" alt="Redes Sociales"/>
                <h2><a href="administrarProductos">Productos</a></h2>
    </div>
</div>

<?php require_once __DIR__ . '/layout/footer.phtml' ?>